language: node_js

node_js:
  - "0.10"

script:
  - gulp build
  - gulp test
  - gulp docs

before_deploy:
  - rm -rf src/test

deploy:

  - provider: npm
    email: peterc@aetheric.co.nz
    skip_cleanup: true
    api_key:
      secure: tzdldb1wfANnkGFsOzy0onyK3cHeBRZb+A5qPYk/yp24KVqxYCTCynlRJq81GZi9S43erkiIRhUqi2+74UHaVjQEl3sTRy3l0pXIsKZBlucH+UsjOhu1kbg0I96AFbNxMJ8MBy7erZmkKPtWAkKGEcaKM4ntVESt9pVMkArjXpZN0rLQcZWBrHFJqC940/1hfdpEHPpZGyrf/a1e+4t+HGMDIA/JYg4RJXBDoFj6nq/TiH1l4kDbeEg+cpZDhXEpmtO510MhDthhInBPUctNUKZAzVo2NPFvAgzvtT0UNbrnM4FCu8bubzWIHSwLgndKj1PI7O5/6Wm12icoYx9KxV7WwTx+cQx1AxyauEOXtl51CRFsREgnM1CcugedtJX4Tp0HG/wvwWL+XZBmoXlB6dpivMd88vKENGo1Ph18TTrQEV+2Hz/Miq6k88IrVwCnI6ngD226cNemNYYkpN6lNBsN3nNCzGeyPmqULLh3qU4vVC68ZvW+LZEt0RfM7Biqr98nsrV7YtwdGlWS+M7uqX6JGtG5b2OBU9F4PGOyPTlJZVBrdoPhdmxtQtKL3fIliXZesn3oQqswAErUeBJkRzAu5lJwSGnaZVmWDGLVwYsfkEBUnZznFEIKth+xY7YLHNZScWZlQBCQekPemLd2+ySNymc3BLj7vdf22uQmu1s=
    on:
      repo: aetheric/express-hateoas
      all_branches: true

  - provider: releases
    skip_cleanup: true
    file:
      - dist/http-constants.js
      - dist/http-constants.min.js
    api_key:
      secure: qUm0M9qS6rDRFjPCrq43QOK7a9qc8ePmlIqjX5x4HYUMhfVn8lGHJn8nHX/JsDdoCUe34Rvv2S+GTV6wCTbZgg5AwCLXOGx8USQZi0RqVrb7E3pENHeBmz3xwrAhLiEc05DOFjsLwrwWEUE2bNRKU9MOf1bIcRGfDFh7Y8lcQ0Gt9i1djDZr3sbCuUUaRRc2FQO4rYfEwDKgYkCD9FWf8U2MfgRNcKwCyFQThJ/eZpJtGJMCHtHOwSmhovL1hmTK5Woj7/uEwfbBNI3Py4bp2ljGmaNyfEEUXgcCDO7bHYLIDMk5vH+a4u+HatGfztgYfVhcQ4zLG5UDfeUAzNgnby3CtcSSJBkTVCyFcWqqjSrBy8v1wD2jB0xwbiOL7roF82fz8QVvNYwNEpTf6SFRMZlMjBBQZuQnfclWS1Hh3vFxA/JuAtQcCArBUdzCK0MP6w5/SMShB2WYzF3QgfSfRgzQWBtTcDHX16QeaxwK92+/HqAlJsQ8UZUCiSTjxlbglzN8W6pW30Ojfg2O+2NLv870lykTXS4dMQksGX2GHX5yxyd/rluZu51BtQqTp+TELIUp7WUnY7YfYW1Mp17MXDDkBgrRDvERW11+W3oPwHorF5QsQ7uZ+lTZR846os7tgYREBH3HTuXDoYEVi7CDsVf98g6zKQhSoCkshSqMdds=
    on:
      tags: true
