language: node_js

node_js:
  - '5.6'

env:
  - CXX=g++-4.8

addons:
  apt:

    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8

before_install:
  - npm install -g npm@latest

after_install:
  - npm config set tag-version-prefix "" --global
  - npm config set tag-version-prefix ""

before_script:
  - npm version `git describe --tags` --no-git-tag
  - cat package.json | grep version

script:
  - gulp build
  - gulp test
  - gulp docs

before_deploy:
  - rm -rf src/test

deploy:
  provider: npm
  email: peterc@aetheric.co.nz
  skip_cleanup: true
  api_key:
    secure: tzdldb1wfANnkGFsOzy0onyK3cHeBRZb+A5qPYk/yp24KVqxYCTCynlRJq81GZi9S43erkiIRhUqi2+74UHaVjQEl3sTRy3l0pXIsKZBlucH+UsjOhu1kbg0I96AFbNxMJ8MBy7erZmkKPtWAkKGEcaKM4ntVESt9pVMkArjXpZN0rLQcZWBrHFJqC940/1hfdpEHPpZGyrf/a1e+4t+HGMDIA/JYg4RJXBDoFj6nq/TiH1l4kDbeEg+cpZDhXEpmtO510MhDthhInBPUctNUKZAzVo2NPFvAgzvtT0UNbrnM4FCu8bubzWIHSwLgndKj1PI7O5/6Wm12icoYx9KxV7WwTx+cQx1AxyauEOXtl51CRFsREgnM1CcugedtJX4Tp0HG/wvwWL+XZBmoXlB6dpivMd88vKENGo1Ph18TTrQEV+2Hz/Miq6k88IrVwCnI6ngD226cNemNYYkpN6lNBsN3nNCzGeyPmqULLh3qU4vVC68ZvW+LZEt0RfM7Biqr98nsrV7YtwdGlWS+M7uqX6JGtG5b2OBU9F4PGOyPTlJZVBrdoPhdmxtQtKL3fIliXZesn3oQqswAErUeBJkRzAu5lJwSGnaZVmWDGLVwYsfkEBUnZznFEIKth+xY7YLHNZScWZlQBCQekPemLd2+ySNymc3BLj7vdf22uQmu1s=
  on:
    repo: aetheric/express-hateoas
    all_branches: true
